# Generated by Django 4.2 on 2023-04-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age_user_gender_user_introduction_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=10, verbose_name='닉네임 또는 이름'),
        ),
    ]
