# Generated by Django 4.2 on 2023-04-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completion_at',
            field=models.DateTimeField(null=True),
        ),
    ]
